services:
  - type: web
    name: vpn-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python scraper.py
    envVars:
      - key: PORT
        value: 8080
    scaling:
      minInstances: 1
      maxInstances: 1